name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
# https://repo1.maven.org/maven2/com/weatherlink/weatherlink-v2-api-sdk/maven-metadata.xml
jobs:
  format:
    name: Format code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install yq
        run: pip3 install yq
      - name: Update README
        run: sed -i 's/<version>.*\?<\/version>/<version>'`curl -s https://repo1.maven.org/maven2/com/weatherlink/weatherlink-v2-api-sdk/maven-metadata.xml | xq '.metadata.versioning.latest' | tr -d '"'`'<\/version>/g' README.md
      - name: Commit README if needed
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update released dependency version in README
          file_pattern: README.md
          skip_dirty_check: false
      - name: Format code
        uses: axel-op/googlejavaformat-action@v3 # for details see https://github.com/axel-op/googlejavaformat-action
        with:
          version: v1.15.0
          args: "--aosp --skip-reflowing-long-strings --replace"
  build:
    name: Build with Java ${{ matrix.Java }}
    needs: format
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '8', '11', '17' ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.Java }}
          cache: 'maven'
      - name: Build with Maven
        run: mvn --batch-mode --no-transfer-progress package --file pom.xml
