name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  format:
    name: Format code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: axel-op/googlejavaformat-action@v3 # for details see https://github.com/axel-op/googlejavaformat-action
        with:
          version: 8
          args: "--aosp --skip-reflowing-long-strings --replace"
  build:
    name: Build with Java ${{ matrix.Java }}
    needs: format
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '8', '11', '17' ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.Java }}
          cache: 'maven'
      - name: Build with Maven
        run: mvn --batch-mode --no-transfer-progress package --file pom.xml
