name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '8', '11', '17' ]
    name: Java ${{ matrix.Java }} build
    steps:
      - name: Checkout Java
        uses: actions/checkout@v2 # v2 minimum required
#      - uses: axel-op/googlejavaformat-action@v3 # for details see https://github.com/axel-op/googlejavaformat-action
#        with:
#          version: 1.12.0
#          args: "--aosp --skip-reflowing-long-strings --replace"
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: '<distribution>'
          java-version: ${{ matrix.Java }}
          cache: 'maven'
      - name: Build with Maven
        run: mvn --batch-mode --no-transfer-progress package --file pom.xml
