name: On Push

on:
  push:
    branches:
      - main

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # v2 minimum required
      - uses: axel-op/googlejavaformat-action@v3
        with:
          version: 1.11.0
          args: "--replace"
