name: On Push

on:
  push:
    branches:
      - main

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # v2 minimum required
      - uses: axel-op/googlejavaformat-action@v3 # for details see https://github.com/axel-op/googlejavaformat-action
        with:
          version: 1.12.0
          args: "--aosp --replace"
